DROP TABLE IF EXISTS `KDI_T_ORGANIZER`;
CREATE TABLE `KDI_T_ORGANIZER` (
  `ORGANIZER_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ORGANIZER_NAME` VARCHAR(500) DEFAULT NULL,
  `ORGANIZER_CONTACT` VARCHAR(255) DEFAULT NULL,
  `ORGANIZER_EMAIL` VARCHAR(255) DEFAULT NULL,
  `ORGANIZER_TELPHONE` VARCHAR(255) DEFAULT NULL,
  `ORGANIZER_MOBILE` VARCHAR(255) DEFAULT NULL,
  `ORGANIZER_ADDRESS` VARCHAR(500) DEFAULT NULL,
  `ORGANIZER_VERIFY_CODE` VARCHAR(255) DEFAULT NULL,
  `ORGANIZER_STATUS` INT(11) DEFAULT '0' COMMENT '0 已注册未验证通过，1已注册并验证通过， 2 注销',
  PRIMARY KEY (`ORGANIZER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

insert into KDI_T_ORGANIZER values(1,'Default','admin','','','','','',1);


ALTER TABLE `KDI_T_USER` ADD COLUMN `ORGANIZER_ID` bigint(20) NULL DEFAULT 1;
ALTER TABLE `KDI_T_USER` ADD COLUMN `C_USER_STATUS` int NULL DEFAULT 1;
ALTER TABLE `KDI_T_FTP` ADD COLUMN `ORGANIZER_ID` bigint(20) NULL DEFAULT 1;
ALTER TABLE `KDI_T_HADOOP` ADD COLUMN `ORGANIZER_ID` bigint(20) NULL DEFAULT 1;
ALTER TABLE `KDI_T_REPOSITORY` ADD COLUMN `ORGANIZER_ID` bigint(20) NULL DEFAULT 1;

update QRTZ_JOB_DETAILS SET JOB_GROUP =1;
update QRTZ_TRIGGERS SET JOB_GROUP =1;
update QRTZ_TRIGGERS SET TRIGGER_GROUP =1;

